# example of instruction yaml

# basics
# model_yaml_path: C:/Workspace/DataScience/ComputerVision/conductor/utils/resources/example/hadamard_exp.yaml
# model_yaml_path: C:/Workspace/DataScience/ComputerVision/conductor/utils/resources/example/mobilenetv3.yaml
model_yaml_path: C:/Workspace/DataScience/ComputerVision/conductor/utils/resources/example/starnet.yaml
# model_yaml_path: mobilenet_v3_small,{'num_classes':100}
data_yaml_path: C:/Workspace/DataScience/ComputerVision/conductor/temp/cifar100.yaml
command: train  # command from cli, indicate the Conductor what to do
task: classify  # task of the model

# training details
epochs: 200
batch_size: 64
device: cuda
world: '[0]'
criterion: CrossEntropyLoss  # below: within default
optimizer: AdamW
scheduler: CosineAnnealingLR
learn_rate: 1e-3
momentum: 0.9
decay: 1e-4
best_metrics: top1_acc

# logging & ckpt details
output_dir: C:/Workspace/DataScience/ComputerVision/conductor/temp/
ckpt: null